version: '3'
services:

  airflowproject:
    image: youtube-image:latest
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./airflow:/opt/airflow
      - ./airflow/data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: airflow standalone

    